name: Deploy to Okteto Cloud
on:
  workflow_dispatch:
  schedule:
    - cron: "10 18 * * *" # 18:10 every day (UTC)
  push:
    branches:
      - main
jobs:
  deployment_using_okteto_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Okteto context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Activate namespace
        uses: okteto/namespace@latest
        with:
          namespace: keikekke

      - name: Trigger the pipeline
        uses: okteto/pipeline@latest
        with:
          name: todo
          timeout: 8m
